<?php
// includes/lang.php
if (session_status() === PHP_SESSION_NONE) {
    @session_start();
}


// ກວດສອບການປ່ຽນພາສາຜ່ານ URL
if (isset($_GET['lang'])) {
    $lang = $_GET['lang'];
    if (in_array($lang, ['lo', 'en'])) {
        $_SESSION['lang'] = $lang;
    }
    // ກັບຄືນໜ້າເກົ່າ ໂດຍບໍ່ມີ parameter ?lang
    $redirect = strtok($_SERVER['REQUEST_URI'], '?');
    // ຮັກສາ query parameters ອື່ນໆ ຖ້າມີ
    $queryParams = $_GET;
    unset($queryParams['lang']);
    if (!empty($queryParams)) {
        $redirect .= '?' . http_build_query($queryParams);
    }
    header("Location: " . $redirect);
    exit;
}

// ພາສາເລີ່ມຕົ້ນແມ່ນ ພາສາລາວ 'lo'
if (!isset($_SESSION['lang'])) {
    $_SESSION['lang'] = 'lo';
}

$current_lang = $_SESSION['lang'];

// ອາເຣແປພາສາ (Translation Dictionary)
$translations = [
    'lo' => [
        'brand_name' => 'LaoFe & Beer',
        'nav_home' => 'ໜ້າຫຼັກ',
        'nav_story' => 'ເລື່ອງລາວຂອງເຮົາ',
        'nav_ourstory' => 'ເລື່ອງລາວຂອງເຮົາ',
        'nav_about' => 'ກ່ຽວກັບເຮົາ',
        'nav_menu' => 'ເມນູ',
        'nav_digital_menu' => 'ເມນູປຶ້ມດິຈິຕອນ',
        'nav_locations' => 'ສາຂາ',
        'nav_news' => 'ຂ່າວສານ & ໂປຣ',
        'nav_franchise' => 'ຮ່ວມທຸລະກິດ',
        'nav_contact' => 'ຕິດຕໍ່',
        'lang_toggle' => 'English',
        'lang_code' => 'en',
        
        // footer
        'footer_contact' => 'ຕິດຕໍ່ພວກເຮົາ',
        'footer_desc' => 'ກາເຟ ແລະ ບາ ໃນຮູບແບບລາວປະຍຸກ ທີ່ຜສານຄວາມເປັນລາວເຂົ້າກັບຄວາມທັນສະໄໝຢ່າງລົງຕົວ.',
        'footer_address' => 'ຖະໜົນສີຫອມ, ບ້ານສີຫອມ, ເມືອງຈັນທະບູລີ, ນະຄອນຫຼວງວຽງຈັນ',
        'footer_admin_title' => 'ການເຂົ້າເຖິງຂອງແອດມິນ',
        'footer_admin_desc' => 'ພອດທໍສຳລັບພະນັກງານເພື່ອຈັດການລາຍການເມນູ ແລະ ຂ່າວສານ.',
        'footer_admin_link' => 'ລະບົບແອດມິນ',
        'footer_rights' => 'ສະຫງວນລິຂະສິດທັງໝົດ.',
        'footer_links' => 'ລິ້ງດ່ວນ',
        'footer_policy' => 'ນະໂຍບາຍຄວາມເປັນສ່ວນຕົວ',
        'footer_terms' => 'ເງື່ອນໄຂການນຳໃຊ້',
        
        // Index / Home page
        'hero_title' => 'ລົດຊາດລາວປະຍຸກ ແທ້ໆ',
        'hero_subtitle' => 'ຄົ້ນພົບຄວາມລົງຕົວຂອງກາເຟຊັ້ນດີໃນຍາມກາງເວັນ ແລະ ເຄື່ອງດື່ມສຸດພິເສດໃນຍາມຄ່ຳຄືນ ທີ່ LaoFe & Beer.',
        'hero_cta' => 'ເບິ່ງເມນູຂອງພວກເຮົາ',
        'promo_title' => 'ໂປຣໂມຊັນພິເສດປະຈຳເດືອນ',
        'promo_sub' => 'ຫ້າມພາດ! ຂໍ້ສະເໜີສຸດຄຸ້ມສຳລັບລູກຄ້າຄົນພິເສດ.',
        'popular_title' => 'ເມນູຍອດນິຍົມ',
        'popular_sub' => 'ລອງເລີຍ! ເມນູທີ່ໄດ້ຮັບຄວາມນິຍົມສູງສຸດຈາກລູກຄ້າຂອງພວກເຮົາ.',
        'view_all' => 'ເບິ່ງທັງໝົດ',
        'learn_more' => 'ອ່ານເພີ່ມເຕີມ',
        'explore_title' => 'ຄົ້ນພົບໂລກແຫ່ງກາເຟ & ບາ ຂອງພວກເຮົາ',
        'high_quality_beans' => 'ແກ່ນກາເຟຄຸນນະພາບສູງ ຈາກບໍລະເວນ',
        'blended_by_champions' => 'ປຸງແຕ່ງໂດຍຜູ້ຊ່ຽວຊານມືອາຊີບ',
        'freshly_roasted_poured' => 'ຂົ້ວສົດໃໝ່ & ດຶງສົດຈາກແທັບ',
        'special_offer' => 'ຂໍ້ສະເໜີສຸດພິເສດ',
        'premium_selection_badge' => 'ກາເຟພຣີມ່ຽມບໍລະເວນທີ່ຄັດສັນເປັນພິເສດ',
        'blended_by_masters' => 'ປຸງແຕ່ງໂດຍທີມງານບາຣິສຕ້າ & ມິກໂຊໂລຈິສ ມືອາຊີບ',
        'meet_experts' => 'ພົບກັບຜູ້ຊ່ຽວຊານດ້ານລົດຊາດຂອງພວກເຮົາ',
        'master_barista' => 'ບາຣິສຕ້າ ມືອາຊີບ',
        'sengdavone_title' => 'ບາຣິສຕ້າ ມືອາຊີບ LaoFe',
        'master_mixologist' => 'ມິກໂຊໂລຈິສ ມືອາຊີບ',
        'bounmy_title' => 'ມິກໂຊໂລຈິສ ມືອາຊີບ LaoFe',
        'master_roaster' => 'ນັກຂົ້ວກາເຟ ມືອາຊີບ',
        'aloun_title' => 'ນັກຂົ້ວກາເຟ ມືອາຊີບ LaoFe',
        'equipment_badge' => 'ອຸປະກອນກາເຟ ແລະ ບາເບຍສົດລະດັບພຣີມ່ຽມ',
        'equipment_title' => 'ຂົ້ວສົດ, ບົດໃໝ່ ແລະ ດຶງສົດຈາກແທັບ',
        'outlets_title' => 'ສາຂາ ແລະ ເລົາຈ໌ ຂອງ LaoFe',
        'outlets_sub' => 'ຊອກຫາສະຖານທີ່ສະດວກສະບາຍໃກ້ທ່ານເພື່ອຜ່ອນຄາຍ ແລະ ເພີດເພີນ',
        'view_map_phone' => 'ເບິ່ງແຜນທີ່ & ເບີໂທ',
        'lounge_sithong' => 'ສາຂາສີທອງ ເລົາຈ໌',
        'lounge_vangvieng' => 'ສາຂາວັງວຽງ ຣິເວີໄຊ້',
        'lounge_luangprabang' => 'ສາຂາຫຼວງພະບາງ ມໍລະດົກ',
        'lounge_pakse' => 'ສາຂາປາກເຊ ບໍລະເວນເລົາຈ໌',
        'sithong_hours' => 'ຖະໜົນສີທອງ, ນະຄອນຫຼວງວຽງຈັນ. ເປີດທຸກວັນ: 07:00 - 23:00',
        'vangvieng_hours' => 'ຖະໜົນກາງ, ເມືອງວັງວຽງ. ເປີດທຸກວັນ: 07:00 - 24:00',
        'luangprabang_hours' => 'ຖະໜົນສີສະຫວ່າງວົງ, ຫຼວງພະບາງ. ເປີດທຸກວັນ: 06:30 - 22:00',
        'pakse_hours' => 'ເສັ້ນທາງເລກທີ 13, ປາກເຊ. ເປີດທຸກວັນ: 07:00 - 22:00',
        
        // Our Story
        'story_title' => 'ເລື່ອງລາວຂອງ LaoFe & Beer',
        'story_subtitle' => 'ຄວາມເປັນມາ ແລະ ແຮງບັນດານໃຈ',
        'story_hero_title1' => 'ການປ່ຽນແປງຄັ້ງໃຫຍ່',
        'story_hero_title2' => 'ກຳລັງມາຮອດ',
        'story_hero_desc' => 'ຄົ້ນພົບລົດຊາດເອກະລັກຂອງ LaoFe & Beer ທີ່ພ້ອມສົ່ງມອບຄວາມສຸກໃຫ້ທຸກຄົນ. ສັມຜັດລົດຊາດກາເຟ ແລະ ເຄື່ອງດື່ມປະຍຸກສູດພິເສດ ເອກະລັກພຽງແຫ່ງດຽວ.',
        'story_hero_cta' => 'ຄົ້ນພົບເມນູພິເສດ',
        'story_p1' => 'ເມື່ອ 5 ປີກ່ອນ, ຮ້ານຂອງພວກເຮົາໄດ້ເລີ່ມຕົ້ນພາຍໃຕ້ຊື່ "Mountain Café" ທີ່ຈຸດຊົມວິວພູເກົ້າຫຼັກ ເສັ້ນທາງລະຫວ່າງກາສີ-ຫຼວງພະບາງ. ຈາກວິສາຫະກິດຂະໜາດນ້ອຍ, ດ້ວຍວິໄສທັດ ແລະ ຄວາມມຸ່ງໝັ້ນ, ພວກເຮົາໄດ້ຜັນຂະຫຍາຍກາຍເປັນທຸລະກິດຂະໜາດໃຫຍ່ພາຍໃຕ້ກຸ່ມບໍລິສັດລາວໃຕ້ ການຄ້າ ແລະ ການລົງທຶນ.',
        'story_p2' => 'ປັດຈຸບັນ, LaoFe Café ບໍ່ພຽງແຕ່ເປັນຮ້ານກາເຟ, ແຕ່ເປັນແບຣນທີ່ພ້ອມຈະຂະຫຍາຍສາຂາໃນຮູບແບບແຟຣນໄຊສ໌, ນຳເອົາລົດຊາດທີ່ເປັນເອກະລັກ ແລະ ປະສົບການທີ່ດີເລີດໄປສູ່ທຸກຄົນ.',
        'story_vision' => 'ວິໄສທັດຂອງພວກເຮົາ',
        'story_vision_desc' => 'ພວກເຮົາຕ້ອງການເປັນແບຣນກາເຟ ແລະ ບາ ລາວປະຍຸກອັນດັບໜຶ່ງ ທີ່ມີມາດຕະຖານລະດັບສາກົນ ແລະ ພ້ອມທີ່ຈະຂະຫຍາຍສາຂາໄປທົ່ວປະເທດ ແລະ ຕ່າງປະເທດ ດ້ວຍລະບົບແຟຣນໄຊສ໌ທີ່ເຂັ້ມແຂງ.',
        
        // About Us (Luckin Style)
        'about_us_title' => 'ກ່ຽວກັບ LaoFe & Beer',
        'about_us_sub' => 'ແບຣນກາເຟ ແລະ ບາ ລາວປະຍຸກ ທີ່ຜ່ານການຄິດຄົ້ນ ແລະ ພັດທະນາຢ່າງບໍ່ຢຸດຢັ້ງ',
        'about_value_prop_title' => 'ຄຸນຄ່າຫຼັກຂອງ LaoFe & Beer',
        'about_high_quality' => 'ຄຸນນະພາບສູງ',
        'about_high_quality_desc' => 'ແກ່ນກາເຟຄຸນນະພາບສູງຈາກແຫຼ່ງປູກບໍລະເວນ ຜ່ານການປຸງແຕ່ງ ແລະ ຂົ້ວຢ່າງພິຖີພິຖັນ ໂດຍທີມງານມືອາຊີບ ທີ່ຕອບໂຈດລົດຊາດຂອງລູກຄ້າໄດ້ຢ່າງສົມບູນແບບ.',
        'about_high_affordability' => 'ລາຄາເຂົ້າເຖິງງ່າຍ',
        'about_high_affordability_desc' => 'ມອບປະສົບການເຄື່ອງດື່ມພຣີມ່ຽມ ໃນລາຄາທີ່ທຸກຄົນສາມາດເພີດເພີນໄດ້ທຸກໆມື້ ໂດຍບໍ່ມີລາຄາບວກເພີ່ມທີ່ເກີນຄວາມເປັນຈິງ.',
        'about_high_convenience' => 'ຄວາມສະດວກສະບາຍສູງ',
        'about_high_convenience_desc' => 'ສະດວກສະບາຍໃນການສັ່ງເຄື່ອງດື່ມ ແລະ ພັກຜ່ອນ ໃນບັນຍາກາດເລົາຈ໌ທີ່ທັນສະໄໝ 4 ສາຂາ ພ້ອມບໍລິການທີ່ວ່ອງໄວ ແລະ ເປັນກັນເອງ.',
        'about_company_title' => 'ບໍລິສັດ',
        'about_company_val' => 'LAOFE & BEER CO., LTD.',
        'about_email_title' => 'ອີເມລຕິດຕໍ່',
        'about_enquiries_title' => 'ສອບຖາມຂໍ້ມູນ & ຂໍ້ສະເໜີແນະ',
        'about_enquiries_hours' => 'ຈັນ - ອາທິດ: 07:00 - 23:00',
        'about_join_title' => 'ຮ່ວມງານກັບເຮົາ / ແຟຣນໄຊສ໌',
        'about_join_sub' => 'ເບິ່ງໂອກາດທາງທຸລະກິດ',
        
        // Menu page
        'menu_all' => 'ທັງໝົດ',
        'menu_coffee' => 'ກາເຟ',
        'menu_drinks' => 'ເຄື່ອງດື່ມ',
        'menu_bar' => 'ບາ / ຄັອກເທວ',
        'menu_food' => 'ອາຫານລາວປະຍຸກ',
        'currency' => 'ກີບ',
        
        // Locations page
        'loc_title' => 'ສາຂາຂອງພວກເຮົາ',
        'loc_sub' => 'LaoFe & Beer ພ້ອມຕ້ອນຮັບທ່ານໃນ 4 ສາຂາທົ່ວປະເທດ',
        'loc_open' => 'ເວລາເປີດ-ປິດ:',
        'loc_phone' => 'ເບີໂທລະສັບ:',
        'loc_map' => 'ແຜນທີ່ Google Maps',
        
        // Franchise page
        'fran_title' => 'ຮ່ວມທຸລະກິດແຟຣນໄຊສ໌',
        'fran_sub' => 'ເຕີບໃຫຍ່ໄປພ້ອມກັບພວກເຮົາ ດ້ວຍໂຄງສ້າງແຟຣນໄຊສ໌ທີ່ເປັນມືອາຊີບ',
        'fran_desc' => 'ຫາກທ່ານມີຄວາມສົນໃຈ ແລະ ຢາກເປັນສ່ວນໜຶ່ງຂອງຄອບຄົວ LaoFe & Beer ໃນການດຳເນີນທຸລະກິດຮ້ານກາເຟ ແລະ ບາ ທີ່ທັນສະໄໝ, ກະລຸນາກອກຟອມຂໍ້ມູນຕິດຕໍ່ດ້ານລຸ່ມນີ້. ທີມງານຂອງພວກເຮົາຈະຕິດຕໍ່ກັບຫາທ່ານໂດຍໄວທີ່ສຸດ.',
        'fran_form_title' => 'ຟອມສະແດງຄວາມຈຳນົງ',
        'fran_name' => 'ຊື່ ແລະ ນາມສະກຸນ',
        'fran_phone' => 'ເບີໂທລະສັບຕິດຕໍ່',
        'fran_email' => 'ອີເມລ',
        'fran_loc' => 'ສາຂາ/ສະຖານທີ່ ທີ່ທ່ານສົນໃຈຢາກເປີດ',
        'fran_msg' => 'ຂໍ້ຄວາມເພີ່ມເຕີມ/ໝາຍເຫດ',
        'fran_submit' => 'ສົ່ງຂໍ້ມູນສະໝັກ',
        'fran_success' => 'ສົ່ງຂໍ້ມູນສະໝັກແຟຣນໄຊສ໌ສຳເລັດແລ້ວ! ທີມງານຈະຕິດຕໍ່ກັບຫາທ່ານໂດຍໄວ.',
        
        // Additional Franchise / App / Checkout translations (lo)
        'fran_why_choose' => 'ເປັນຫຍັງຕ້ອງເລືອກ LaoFe & Beer?',
        'fran_why_choose_desc' => 'LaoFe & Beer ແມ່ນແບຣນກາເຟ ແລະ ບາ ຍຸກໃໝ່ທີ່ໄດ້ຮັບຄວາມນິຍົມສູງ ແລະ ມີການເຕີ补ຢ່າງຕໍ່ເນື່ອງ. ພວກເຮົາສະເໜີໂອກາດທາງທຸລະກິດທີ່ໝັ້ນຄົງ ແລະ ລະບົບສະໜັບສະໜູນທີ່ຄົບວົງຈອນ.',
        'fran_benefit_1_title' => 'ແນວຄິດຮ້ານແບບ 2-in-1 (ກາເຟ & ບາ)',
        'fran_benefit_1_desc' => 'ສ້າງລາຍຮັບໄດ້ທັງກາງເວັນ (ກາເຟ/ເຄື່ອງດື່ມ) ແລະ ກາງຄືນ (ບາ/ອາຫານປະຍຸກ).',
        'fran_benefit_2_title' => 'ວັດຖຸດິບ ແລະ ສູດສະເພາະຕົວ',
        'fran_benefit_2_desc' => 'ການສະໜອງແກ່ນກາເຟ ແລະ ວັດຖຸດິບຄຸນນະພາບສູງ ພ້ອມສູດເຄື່ອງດື່ມທີ່ເປັນເອກະລັກ.',
        'fran_benefit_3_title' => 'ລະບົບຫຼັງບ້ານ ແລະ ການຕະຫຼາດ',
        'fran_benefit_3_desc' => 'ມີລະບົບຈັດການຮ້ານທີ່ທັນສະໄໝ ແລະ ທີມງານການຕະຫຼາດມືອາຊີບຄອຍຊ່ວຍເຫຼືອ.',
        'fran_loc_placeholder' => 'ເຊັ່ນ: ແຂວງສະຫວັນນະເຂດ, ວຽງຈັນ, ...',
        'app_login_to_earn' => 'ເຂົ້າສູ່ລະບົບເພື່ອສະສົມຄະແນນ',
        'app_collect_points_free' => 'ສະສົມຄະແນນແລກເຄື່ອງດື່ມຟຣີ',
        'app_popular_menu' => 'ເມນູຍອດນິຍົມ',
        'app_order_now' => 'Order Now (ສັ່ງເລີຍ)',
        'app_coming_soon_alert' => 'ພົບກັນໄວໆນີ້!',
        'app_notify_title' => 'ຮັບການແຈ້ງເຕືອນເມື່ອແອັບເປີດໃຫ້ບໍລິການ',
        'app_notify_placeholder' => 'ອີເມລຂອງທ່ານ (Email Address)',
        'app_notify_submit' => 'ສົ່ງຂໍ້ມູນ',
        'app_one_for_all' => 'ແອັບດຽວຄົບທຸກບໍລິການ',
        'app_one_for_all_desc' => 'ຄົ້ນພົບຟີເຈີຫຼັກທີ່ຈະມາຊ່ວຍເພີ່ມຄວາມສະດວກສະບາຍໃຫ້ກັບປະສົບການກາເຟ ແລະ ບາຂອງທ່ານ',
        'app_reg_success_alert' => 'ຂອບໃຈສໍາລັບການລົງທະບຽນ! ລະບົບຈະແຈ້ງເຕືອນຫາອີເມລ',
        'app_reg_empty_alert' => 'ກະລຸນາກອກອີເມລຂອງທ່ານກ່ອນ.',
        'checkout_cart_items' => 'ລາຍການໃນຕະກ້າ',
        'checkout_points_earn' => 'ຄະແນນທີ່ຈະໄດ້ຮັບຈາກອໍເດີ້ວນີ້',
        'checkout_receiver_info' => 'ຂໍ້ມູນຜູ້ຮັບອໍເດີ້',
        'payment_invalid_order' => 'ອໍເດີ້ບໍ່ຖືກຕ້ອງ ຫຼື ບໍ່ພົບໃນລະບົບ.',
        
        // Contact page
        'contact_title' => 'ຕິດຕໍ່ພວກເຮົາ',
        'contact_sub' => 'ມີຄຳຖາມ ຫຼື ຂໍ້ສະເໜີແນະໃດໆ? ສາມາດສົ່ງຫາພວກເຮົາໄດ້ທັນທີ',
        'contact_info' => 'ຂໍ້ມູນຕິດຕໍ່',
        'contact_badge' => 'ຕິດຕໍ່ພວກເຮົາ',
        'contact_desc' => 'ພວກເຮົາຍິນດີຮັບຟັງທຸກຄຳຄິດເຫັນ, ຂໍ້ສະເໜີແນະ ຫຼື ຄຳຖາມຈາກທ່ານ. ທ່ານສາມາດຕິດຕໍ່ຫາພວກເຮົາໂດຍກົງຜ່ານຊ່ອງທາງຕິດຕໍ່ຫຼັກ ຫຼື ສົ່ງຂໍ້ຄວາມຜ່ານຟອມທາງຂ້າງໄດ້.',
        'contact_form_title' => 'ສົ່ງຂໍ້ຄວາມຫາພວກເຮົາ',
        'contact_name' => 'ຊື່ຂອງທ່ານ',
        'contact_phone' => 'ເບີໂທລະສັບ (ຖ້າມີ)',
        'contact_email' => 'ອີເມລ',
        'contact_subject' => 'ຫົວຂໍ້',
        'contact_msg' => 'ຂໍ້ຄວາມຂອງທ່ານ',
        'contact_submit' => 'ສົ່ງຂໍ້ຄວາມ',
        'contact_success' => 'ສົ່ງຂໍ້ຄວາມສຳເລັດແລ້ວ! ຂອບໃຈສຳລັບການຕິດຕໍ່ຫາພວກເຮົາ.',
        
        // Mobile App Page
        'nav_app' => 'ແອັບ LaoFe',
        'app_title' => 'ແອັບມືຖື LaoFe',
        'app_sub' => 'ປະສົບການກາເຟ ແລະ ບາທີ່ສະດວກສະບາຍໃນມືທ່ານ',
        'app_coming_soon' => 'ພົບກັນໄວໆນີ້!',
        'app_desc' => 'ກຽມພົບກັບແອັບພລິເຄຊັນ LaoFe ທີ່ຈະຊ່ວຍໃຫ້ການສັ່ງຊື້ ແລະ ຮັບບໍລິການຂອງທ່ານສະດວກສະບາຍກວ່າເກົ່າ. ບໍ່ວ່າຈະເປັນການສັ່ງກາເຟໄວ້ລ່ວງໜ້າ, ການສະສົມຄະແນນ ຫຼື ການຈອງໂຕະອອນໄລນ໌.',
        'app_feature_1_title' => 'ສັ່ງຊື້ອອນໄລນ໌ & ຊຳລະເງິນສະດວກ',
        'app_feature_1_desc' => 'ເລືອກເມນູກາເຟ ຫຼື ເຄື່ອງດື່ມທີ່ທ່ານມັກ ແລະ ຊຳລະເງິນລ່ວງໜ້າຜ່ານ OnePay ໄດ້ງ່າຍໆ ເພື່ອຮັບເຄື່ອງໂດຍບໍ່ຕ້ອງຖ້າຄິວ.',
        'app_feature_2_title' => 'ລະບົບສະມາຊິກ & ສະສົມຄະແນນ',
        'app_feature_2_desc' => 'ສະສົມຄະແນນໃນທຸກໆຈອກທີ່ທ່ານຊື້ ເພື່ອແລກຮັບເຄື່ອງດື່ມຟຣີ ຫຼື ສິດທິພິເສດສະເພາະສະມາຊິກ LaoFe.',
        'app_feature_3_title' => 'ລະບົບຈອງໂຕະອອນໄລນ໌',
        'app_feature_3_desc' => 'ຈອງໂຕະ ຫຼື ໂຊນນັ່ງຫຼິ້ນລະດັບພຣີມ່ຽມທີ່ສາຂາສີທອງ ຫຼື ວັງວຽງລ່ວງໜ້າ ເພື່ອຄວາມສະດວກສະບາຍໃນການພົບປະສັງສັນ.',
        'app_feature_4_title' => 'ໂປຣໂມຊັນພິເສດສະເພາະແອັບ',
        'app_feature_4_desc' => 'ຮັບຄູປອງສ່ວນຫຼຸດພິເສດ ແລະ ຂໍ້ສະເໜີດີໆ ທີ່ສະເໜີໃຫ້ສະເພາະຜູ້ໃຊ້ແອັບພລິເຄຊັນ LaoFe ເທົ່ານັ້ນ.',
        
        // Phase 2 translations (lo)
        'nav_cart' => 'ຕະກ້າສິນຄ້າ',
        'nav_checkout' => 'ຊຳລະເງິນ',
        'nav_booking' => 'ຈອງໂຕະ',
        'nav_login' => 'ເຂົ້າສູ່ລະບົບ',
        'nav_register' => 'ລົງທະບຽນ',
        'nav_account' => 'ບັນຊີສະມາຊິກ',
        'cart_empty' => 'ຕະກ້າສິນຄ້າຂອງທ່ານວ່າງເປົ່າ.',
        'cart_total' => 'ຍອດລວມທັງໝົດ',
        'btn_checkout' => 'ດຳເນີນການຊຳລະເງິນ',
        'btn_add_cart' => 'ເພີ່ມໃສ່ຕະກ້າ',
        'order_placed_success' => 'ສັ່ງຊື້ສຳເລັດແລ້ວ!',
        'points_label' => 'ຄະແນນສະສົມ',
        'tier_label' => 'ລະດັບສະມາຊິກ',
        'no_history' => 'ຍັງບໍ່ມີປະຫວັດການເຮັດວຽກ',
        'order_id' => 'ເລກບິນອໍເດີ້',
        'order_date' => 'ວັນທີ',
        'order_status' => 'ສະຖານະ',
        'order_total' => 'ຍອດລວມ',
        'booking_date_label' => 'ວັນທີຈອງ',
        'booking_time_label' => 'ເວລາ',
        'booking_guests' => 'ຈຳນວນຄົນ',
        'booking_zone' => 'ໂຊນ',
        'booking_invalid' => 'ລາຍການຈອງໂຕະບໍ່ຖືກຕ້ອງ ຫຼື ບໍ່ພົບໃນລະບົບ.',

        // Member Account Portal (lo)
        'acc_welcome' => 'ສະບາຍດີ, ທ່ານ',
        'acc_subtitle' => 'ນີ້ແມ່ນສະຫຼຸບຂໍ້ມູນ LaoFe & Beer ຂອງທ່ານໃນມື້ນີ້.',
        'acc_tab_dashboard' => 'ໜ້າຫຼັກສະມາຊິກ',
        'acc_tab_reservations' => 'ປະຫວັດການຈອງໂຕະ',
        'acc_tab_orders' => 'ປະຫວັດການສັ່ງຊື້',
        'acc_tab_loyalty' => 'ບັດສະມາຊິກ & ສິດທິພິເສດ',
        'acc_tab_settings' => 'ຕັ້ງຄ່າຂໍ້ມູນສ່ວນຕົວ',
        'acc_loyalty_title' => '🔥 ຄະແນນສະສົມ (LOYALTY REWARDS)',
        'acc_pts' => 'ຄະແນນ',
        'acc_points_away' => 'ອີກ %s ຄະແນນ ເພື່ອຮັບສິດທິພິເສດໃນ Tier ຖັດໄປ.',
        'acc_current_tier' => 'TIER ປັດຈຸບັນ:',
        'acc_next_reward' => 'ຖັດໄປ: ແລກຮັບເຄື່ອງດື່ມ / ກາເຟພຣີມ່ຽມຟຣີ',
        'acc_upcoming_title' => '📅 ການຈອງໂຕະໃນໄວໆນີ້',
        'acc_no_upcoming' => 'ບໍ່ມີລາຍການຈອງໂຕະໃນໄວໆນີ້',
        'acc_book_now' => 'ຈອງໂຕະ / ສັ່ງເລີຍ',
        'acc_recent_orders' => '📜 ປະຫວັດການສັ່ງຊື້ຫຼ້າສຸດ',
        'acc_view_all' => 'ເບິ່ງທັງໝົດ',
        'acc_no_orders' => 'ຍັງບໍ່ມີປະຫວັດການສັ່ງຊື້',
        'acc_quick_settings' => '⚙️ ທາງລັດຕັ້ງຄ່າ',
        'acc_edit_profile' => 'ແກ້ໄຂຂໍ້ມູນສ່ວນຕົວ',
        'acc_loyalty_card' => 'ບັດສະມາຊິກ',
        'acc_order_now_btn' => '🛒 ສັ່ງເຄື່ອງດື່ມ / ອາຫານ',
        'acc_logout' => 'ອອກຈາກລະບົບ',
        'acc_crafting_title' => 'ສ້າງສັນທຸກຊ່ວງເວລາອັນແສນພິເສດ.',
        'acc_crafting_desc' => 'ຄົ້ນພົບເມນູກາເຟຂົ້ວສົດ, ເຄື່ອງດື່ມປະຍຸກ ແລະ ເບຍສົດ ຄຸນນະພາບພຣີມ່ຽມ ທີ່ LaoFe & Beer.',
        'acc_explore_menu' => 'ຄົ້ນພົບເມນູຂອງພວກເຮົາ',
        'acc_digital_card' => '💳 ບັດສະມາຊິກດິຈິຕອນ',
        'acc_tier_benefits' => '🏆 ສິດທິພິເສດຕາມລະດັບສະມາຊິກ',
        'acc_tier_member_desc' => '• ສະສົມຄະແນນ 1,000₭ = 1 Pts',
        'acc_tier_silver_desc' => '• ຮັບສ່ວນຫຼຸດເຄື່ອງດື່ມ 5%',
        'acc_tier_gold_desc' => '• ຮັບສ່ວນຫຼຸດ 10% + ເຄື່ອງດື່ມວັນເກີດຟຣີ',
        'acc_edit_profile_title' => '⚙️ ແກ້ໄຂຂໍ້ມູນສ່ວນຕົວ',
        'acc_fullname' => 'ຊື່ ແລະ ນາມສະກຸນ',
        'acc_phone' => 'ເບີໂທລະສັບ',
        'acc_email' => 'ອີເມລ (Email)',
        'acc_new_pass' => 'ລະຫັດຜ່ານໃໝ່ (ປະວ່າງໄວ້ຖ້າບໍ່ຕ້ອງການປ່ຽນ)',
        'acc_save_btn' => 'ບັນທຶກການປ່ຽນແປງ',
    ],
    'en' => [
        'brand_name' => 'LaoFe & Beer',
        'nav_home' => 'Home',
        'nav_story' => 'Our Story',
        'nav_ourstory' => 'Our Story',
        'nav_about' => 'About Us',
        'nav_menu' => 'Menu',
        'nav_digital_menu' => 'Booklet Menu',
        'nav_locations' => 'Locations',
        'nav_news' => 'News & Promos',
        'nav_franchise' => 'Franchise',
        'nav_contact' => 'Contact Us',
        'lang_toggle' => 'ພາສາລາວ',
        'lang_code' => 'lo',
        
        // footer
        'footer_contact' => 'Contact Us',
        'footer_desc' => 'A Lao-adapted coffee & bar concept that blends traditional Lao culture with modern lifestyle.',
        'footer_address' => 'Sihom Road, Sihom Village, Chanthabouly District, Vientiane Capital',
        'footer_admin_title' => 'Admin Access',
        'footer_admin_desc' => 'Portal for staff members to manage menu items and news.',
        'footer_admin_link' => 'Admin Panel',
        'footer_rights' => 'All rights reserved.',
        'footer_links' => 'Quick Links',
        'footer_policy' => 'Privacy Policy',
        'footer_terms' => 'Terms of Use',
        
        // Index / Home page
        'hero_title' => 'Authentic Lao-Adapted Taste',
        'hero_subtitle' => 'Discover the perfect blend of premium coffee by day and craft beverages by night at LaoFe & Beer.',
        'hero_cta' => 'Explore Our Menu',
        'promo_title' => 'Special Monthly Promotions',
        'promo_sub' => 'Do not miss out on exclusive offers tailored just for you.',
        'popular_title' => 'Popular Items',
        'popular_sub' => 'Try our most-ordered coffee, drinks, and food items.',
        'view_all' => 'View All',
        'learn_more' => 'Read More',
        'explore_title' => 'Explore Our Coffee & Bar World',
        'high_quality_beans' => 'HIGH QUALITY BOLAVEN BEANS',
        'blended_by_champions' => 'BLENDED BY MASTER CRAFTSMEN',
        'freshly_roasted_poured' => 'FRESHLY ROASTED & DRAFT POURED',
        'special_offer' => 'Special Offer',
        'premium_selection_badge' => 'Premium Bolaven Coffee Selection',
        'blended_by_masters' => 'Blended by Professional Baristas & Mixologists',
        'meet_experts' => 'Meet our experts behind the perfect taste',
        'master_barista' => 'Professional Barista',
        'sengdavone_title' => 'LaoFe Professional Barista',
        'master_mixologist' => 'Professional Mixologist',
        'bounmy_title' => 'LaoFe Professional Mixologist',
        'master_roaster' => 'Professional Roaster',
        'aloun_title' => 'LaoFe Professional Coffee Roaster',
        'equipment_badge' => 'Premium Coffee & Draft Bar Equipment',
        'equipment_title' => 'Freshly Roasted, Freshly Grounded & Drafted',
        'outlets_title' => 'LaoFe Outlets & Lounges',
        'outlets_sub' => 'Find a comfortable spot near you to relax and enjoy',
        'view_map_phone' => 'View Map & Phone',
        'lounge_sithong' => 'Sithong Lounge',
        'lounge_vangvieng' => 'Vangvieng Riverside',
        'lounge_luangprabang' => 'Luang Prabang Heritage',
        'lounge_pakse' => 'Pakse Bolaven Lounge',
        'sithong_hours' => 'Sithong Road, Vientiane Capital. Open daily: 07:00 - 23:00',
        'vangvieng_hours' => 'Kang Road, Vangvieng Town. Open daily: 07:00 - 24:00',
        'luangprabang_hours' => 'Sisavangvong Road, Luang Prabang. Open daily: 06:30 - 22:00',
        'pakse_hours' => 'Route 13, Pakse City. Open daily: 07:00 - 22:00',
        
        // Our Story
        'story_title' => 'Our Story - LaoFe & Beer',
        'story_subtitle' => 'Origin and Inspiration',
        'story_hero_title1' => 'The Real Game Changer',
        'story_hero_title2' => 'is Coming',
        'story_hero_desc' => 'Discover the signature taste of LaoFe & Beer, meant to be shared with all. Taste the original Lao-adapted coffee & craft beverages only at LaoFe & Beer.',
        'story_hero_cta' => 'Explore Exclusive Menu',
        'story_p1' => '5 years ago, our business started under the name "Mountain Café" at the Phou Kao Lak viewpoint along the Kasi–Luang Prabang route. From a small enterprise, driven by vision and dedication, we expanded into a large-scale business under the Lao Tai Trading and Investment Group.',
        'story_p2' => 'Currently, LaoFe Café is not only a coffee shop, but a brand ready to expand through franchising, bringing unique flavors and exceptional experiences to everyone.',
        'story_vision' => 'Our Vision',
        'story_vision_desc' => 'To be the leading Lao-adapted coffee and bar brand with international standards, ready to expand nationwide and globally through a robust franchise system.',
        
        // Menu page
        'menu_all' => 'All',
        'menu_coffee' => 'Coffee',
        'menu_drinks' => 'Drinks',
        'menu_bar' => 'Bar / Cocktails',
        'menu_food' => 'Lao-Adapted Food',
        'currency' => 'LAK',
        
        // Locations page
        'loc_title' => 'Our Branches',
        'loc_sub' => 'LaoFe & Beer is ready to welcome you in 4 branches nationwide',
        'loc_open' => 'Opening Hours:',
        'loc_phone' => 'Phone:',
        'loc_map' => 'View Google Maps',
        
        // Franchise page
        'fran_title' => 'Join Our Franchise',
        'fran_sub' => 'Grow with us through a highly professional franchise structure',
        'fran_desc' => 'If you are interested in joining the LaoFe & Beer family and operating a modern coffee & bar outlet, please fill out the contact form below. Our team will contact you shortly.',
        'fran_form_title' => 'Franchise Inquiry Form',
        'fran_name' => 'Full Name',
        'fran_phone' => 'Contact Phone',
        'fran_email' => 'Email Address',
        'fran_loc' => 'Preferred Location / Branch',
        'fran_msg' => 'Additional Message / Notes',
        'fran_submit' => 'Submit Application',
        'fran_success' => 'Franchise inquiry submitted successfully! Our team will contact you soon.',
        
        // Additional Franchise / App / Checkout translations (en)
        'fran_why_choose' => 'Why choose LaoFe & Beer?',
        'fran_why_choose_desc' => 'LaoFe & Beer is a new-era coffee & bar brand with high popularity and continuous growth. We offer stable business opportunities and a comprehensive support system.',
        'fran_benefit_1_title' => '2-in-1 Shop Concept (Coffee & Bar)',
        'fran_benefit_1_desc' => 'Generate revenue during the day (coffee/drinks) and at night (draft bar/adapted food).',
        'fran_benefit_2_title' => 'Proprietary Recipes & Quality Sourcing',
        'fran_benefit_2_desc' => 'Supply of high-quality Bolaven beans and raw materials with unique beverage recipes.',
        'fran_benefit_3_title' => 'Management Systems & Marketing',
        'fran_benefit_3_desc' => 'Modern point-of-sale shop management system and support from a professional marketing team.',
        'fran_loc_placeholder' => 'e.g., Savannakhet, Vientiane, ...',
        'app_login_to_earn' => 'Login to earn rewards points',
        'app_collect_points_free' => 'Collect points to get free drinks',
        'app_popular_menu' => 'Popular Menu',
        'app_order_now' => 'Order Now',
        'app_coming_soon_alert' => 'Coming soon!',
        'app_notify_title' => 'Get Notified When App Launches',
        'app_notify_placeholder' => 'Your email address',
        'app_notify_submit' => 'Subscribe',
        'app_one_for_all' => 'One App for All Services',
        'app_one_for_all_desc' => 'Discover the core features that will bring ultimate convenience to your coffee and lounge experience.',
        'app_reg_success_alert' => 'Thank you for registering! We will notify you at',
        'app_reg_empty_alert' => 'Please enter your email address first.',
        'checkout_cart_items' => 'Cart Items',
        'checkout_points_earn' => 'Points to be earned from this order',
        'checkout_receiver_info' => 'Receiver Information',
        'payment_invalid_order' => 'Invalid order or order not found in the system.',
        
        // Contact page
        'contact_title' => 'Contact Us',
        'contact_sub' => 'Have questions or suggestions? Reach out to us anytime',
        'contact_info' => 'Contact Information',
        'contact_badge' => 'CONTACT US',
        'contact_desc' => 'We are happy to hear from you. Send us a message or reach us directly.',
        'contact_form_title' => 'Send Us a Message',
        'contact_name' => 'Your Name',
        'contact_phone' => 'Phone Number (Optional)',
        'contact_email' => 'Email Address',
        'contact_subject' => 'Subject',
        'contact_msg' => 'Your Message',
        'contact_submit' => 'Send Message',
        'contact_success' => 'Message sent successfully! Thank you for contacting us.',
        
        // About Us (Luckin Style)
        'about_us_title' => 'About LaoFe & Beer',
        'about_us_sub' => 'A leading Lao-adapted coffee & bar brand driven by quality, value, and convenience',
        'about_value_prop_title' => "LaoFe & Beer's Value Proposition",
        'about_high_quality' => 'HIGH QUALITY',
        'about_high_quality_desc' => 'Top Bolaven Plateau coffee beans carefully blended and roasted to perfection to suit your taste.',
        'about_high_affordability' => 'HIGH AFFORDABILITY',
        'about_high_affordability_desc' => 'Delivering high-end specialty coffee and craft beverages at truly accessible prices for everyday enjoyment.',
        'about_high_convenience' => 'HIGH CONVENIENCE',
        'about_high_convenience_desc' => 'Seamless ordering and modern lounge atmospheres across 4 prime locations with warm, friendly service.',
        'about_company_title' => 'Company',
        'about_company_val' => 'LAOFE & BEER CO., LTD.',
        'about_email_title' => 'E-mail',
        'about_enquiries_title' => 'General Enquiries & Feedback',
        'about_enquiries_hours' => 'Monday to Sunday: 7:00 AM - 11:00 PM',
        'about_join_title' => 'Join Us / Franchise',
        'about_join_sub' => 'See business opportunities',
        
        // Mobile App Page
        'nav_app' => 'Get the APP',
        'app_title' => 'LaoFe Mobile Application',
        'app_sub' => 'Specialty Coffee & Lounge Experience in Your Hands',
        'app_coming_soon' => 'Coming Soon!',
        'app_desc' => 'Get ready for the LaoFe App. Designed to bring convenience to your daily coffee run and lounge visits. Order ahead, collect rewards, and reserve tables seamlessly.',
        'app_feature_1_title' => 'Easy Online Ordering & Payment',
        'app_feature_1_desc' => 'Select your favorite coffee or lounge drinks, customize your cup, and pay securely via OnePay or card to skip the line.',
        'app_feature_2_title' => 'LaoFe Loyalty & Rewards',
        'app_feature_2_desc' => 'Earn reward points with every purchase to redeem free drinks, special merchandise, and exclusive members-only perks.',
        'app_feature_3_title' => 'Online Table & Lounge Booking',
        'app_feature_3_desc' => 'Reserve premium seating or private lounge tables at Sithong or Vangvieng branches in advance for your meetings and parties.',
        'app_feature_4_title' => 'Exclusive In-App Promotions',
        'app_feature_4_desc' => 'Unlock instant vouchers, buy-1-get-1 offers, and special discount codes available exclusively inside the LaoFe app.',
        
        // Phase 2 translations (en)
        'nav_cart' => 'Shopping Cart',
        'nav_checkout' => 'Checkout',
        'nav_booking' => 'Book Table',
        'nav_login' => 'Login',
        'nav_register' => 'Register',
        'nav_account' => 'My Account',
        'cart_empty' => 'Your cart is empty.',
        'cart_total' => 'Total Amount',
        'btn_checkout' => 'Proceed to Checkout',
        'btn_add_cart' => 'Add to Cart',
        'order_placed_success' => 'Order placed successfully!',
        'points_label' => 'Total Points',
        'tier_label' => 'Membership Tier',
        'no_history' => 'No history found',
        'order_id' => 'Order ID',
        'order_date' => 'Date',
        'order_status' => 'Status',
        'order_total' => 'Total',
        'booking_date_label' => 'Booking Date',
        'booking_time_label' => 'Time',
        'booking_guests' => 'Guests',
        'booking_zone' => 'Zone',
        'booking_invalid' => 'Invalid booking or booking not found in the system.',

        // Member Account Portal (en)
        'acc_welcome' => 'Welcome back,',
        'acc_subtitle' => 'Here is your LaoFe & Beer summary for today.',
        'acc_tab_dashboard' => 'Dashboard',
        'acc_tab_reservations' => 'Reservations',
        'acc_tab_orders' => 'Order History',
        'acc_tab_loyalty' => 'Loyalty Club',
        'acc_tab_settings' => 'Settings',
        'acc_loyalty_title' => '🔥 LOYALTY REWARDS',
        'acc_pts' => 'Points',
        'acc_points_away' => 'You are %s points away from your next reward item.',
        'acc_current_tier' => 'CURRENT TIER:',
        'acc_next_reward' => 'NEXT: FREE CRAFT BEER / SPECIALTY COFFEE',
        'acc_upcoming_title' => '📅 UPCOMING',
        'acc_no_upcoming' => 'No upcoming reservations',
        'acc_book_now' => 'Book Table / Order Now',
        'acc_recent_orders' => '📜 Recent Orders',
        'acc_view_all' => 'View All',
        'acc_no_orders' => 'No recent orders yet',
        'acc_quick_settings' => '⚙️ Quick Settings',
        'acc_edit_profile' => 'Edit Profile',
        'acc_loyalty_card' => 'Loyalty Card',
        'acc_order_now_btn' => '🛒 Order Now',
        'acc_logout' => 'Logout',
        'acc_crafting_title' => 'Crafting Moments.',
        'acc_crafting_desc' => 'Discover our latest seasonal brews, single-origin roasts, and craft beers designed for great moments.',
        'acc_explore_menu' => 'Explore Menu',
        'acc_digital_card' => '💳 Digital Member Card',
        'acc_tier_benefits' => '🏆 Tier Privileges & Benefits',
        'acc_tier_member_desc' => '• Earn 1 Pts for every 1,000 LAK spent',
        'acc_tier_silver_desc' => '• 5% discount on all beverages',
        'acc_tier_gold_desc' => '• 10% discount + Free birthday beverage',
        'acc_edit_profile_title' => '⚙️ Edit Profile',
        'acc_fullname' => 'Full Name',
        'acc_phone' => 'Phone Number',
        'acc_email' => 'Email Address',
        'acc_new_pass' => 'New Password (Leave blank to keep unchanged)',
        'acc_save_btn' => 'Save Changes',
    ]
];

// ຟັງຊັນແປຄຳສັບ (Translation helper)
function t($key) {
    global $translations, $current_lang;
    if (isset($translations[$current_lang][$key])) {
        return $translations[$current_lang][$key];
    }
    return $key;
}

// ຟັງຊັນດຶງຂໍ້ມູນຈາກ Database ແປພາສາຕາມຟິວ (e.g. name_lo vs name_en)
function td($row, $field) {
    global $current_lang;
    $field_lang = $field . '_' . $current_lang;
    if (isset($row[$field_lang]) && $row[$field_lang] !== '') {
        return $row[$field_lang];
    }
    // ຖ້າບໍ່ມີ ໃຫ້ກັບໄປໃຊ້ ພາສາລາວ (lo)
    $field_default = $field . '_lo';
    return isset($row[$field_default]) ? $row[$field_default] : '';
}
?>
